# Generated by Django 2.1.2 on 2019-03-03 16:53

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concelho',
            fields=[
                ('nome', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('nome', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Freguesy',
            fields=[
                ('nome', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
                ('concelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Concelho')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.District')),
            ],
        ),
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_id', models.CharField(default='', max_length=350)),
                ('active_principle', models.CharField(default='', max_length=150)),
                ('dosage', models.CharField(default='', max_length=50)),
                ('farmaceutical_form', models.CharField(default='', max_length=100)),
                ('packaging', models.IntegerField(default=0)),
                ('quantity_stock', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=150)),
                ('cnpem', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_notificado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_utente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_pensionistas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('description', models.CharField(default='', max_length=100)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('med', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicamentos.Med')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100, verbose_name='Morada')),
                ('postal_code', models.CharField(default='', max_length=8, verbose_name='Código Postal')),
                ('localidade', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=None, null=True, verbose_name='Número de telefone')),
                ('latitude', models.CharField(default='', max_length=50, null=True)),
                ('longitude', models.CharField(default='', max_length=50, null=True)),
                ('active', models.BooleanField(default=False, verbose_name='Elegível')),
                ('freguesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Freguesy')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Pharmacy'),
        ),
        migrations.AddField(
            model_name='order',
            name='utente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utentes.Utente'),
        ),
        migrations.AddField(
            model_name='concelho',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.District'),
        ),
        UnaccentExtension()
    ]
