# Generated by Django 2.1.7 on 2019-04-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_order_order_no'),
        ('medicamentos', '0002_auto_20190228_2151'),
    ]

    operations = [
    ]
