# Generated by Django 2.0.5 on 2019-04-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0006_auto_20190414_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('med', 'warehouse')},
        ),
    ]
