# Generated by Django 2.0.5 on 2019-04-15 17:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0007_auto_20190415_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='county',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='district',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.District'),
            preserve_default=False,
        ),
    ]
