# Generated by Django 2.0.5 on 2019-04-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0009_auto_20190415_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='warehouse_id',
            new_name='w_id',
        ),
    ]
