# Generated by Django 2.1.2 on 2019-04-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0011_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='med',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med', to='medicamentos.Med'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='medicamentos.Warehouse'),
        ),
    ]
