# Generated by Django 2.0.5 on 2019-04-14 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 3, 21, 38, 381836)),
        ),
    ]
