# Generated by Django 2.0.5 on 2019-04-14 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utentes', '0002_utente_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 3, 23, 35, 180156)),
        ),
    ]
