# Generated by Django 2.0.5 on 2019-04-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utentes', '0003_auto_20190414_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
