# Generated by Django 2.1.2 on 2019-04-18 14:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utentes', '0004_auto_20190414_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('morada', models.CharField(default='', max_length=255)),
                ('contact_name', models.CharField(default='', max_length=255)),
                ('contact_email', models.CharField(default='', max_length=255)),
                ('contact_phone', models.IntegerField(null=True)),
                ('postal_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=8), size=None)),
            ],
        ),
    ]
